# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Nameb

# Model Form Field configuration
form: $/waka/publisher/models/nameb/fields.yaml

# Model Class name
modelClass: Waka\Publisher\Models\Nameb

# Default redirect location
defaultRedirect: waka/publisher/namebs

# Create page
create:
    title: Create Nameb
    redirect: waka/publisher/namebs/update/:id
    redirectClose: waka/publisher/namebs

# Update page
update:
    title: Edit Nameb
    redirect: waka/publisher/namebs
    redirectClose: waka/publisher/namebs

# Preview page
preview:
    title: Preview Nameb
