# ===================================
#  Form Field Definitions
# ===================================

fields:
    sector:
        label: waka.publisher::lang.staticconfig.sector
        type: dropdown
        options: listNestedSector
    data:
        label: waka.importexport::lang.comon.config
        type: codeeditor
        language: yaml
        


