# ===================================
#  Reorder Behavior Config
# ===================================

# Reorder Title
title: Reorder documents

# Attribute name
nameFrom: name

# Model Class name
modelClass: Waka\Publisher\Models\Document

# Toolbar widget configuration
#toolbar:
    # Partial for toolbar buttons
    # buttons: reorder_toolbar