# ===================================
#  Relation Behavior Config
# ===================================




blocs:
    label: waka.publisher::lang.bloc.code
    manage:
        form: $/waka/publisher/models/bloc/fields.yaml
    view:
        list: $/waka/publisher/models/bloc/columns_for_document.yaml
        toolbarButtons: create|delete
        defaultSort:
            column: sort_order
            direction: asc



