# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Bloc Name

# Model Form Field configuration
form: $/waka/publisher/models/blocname/fields.yaml

# Model Class name
modelClass: Waka\Publisher\Models\BlocName

# Default redirect location
defaultRedirect: waka/publisher/blocnames

# Create page
create:
    title: Create Bloc Name
    redirect: waka/publisher/blocnames/update/:id
    redirectClose: waka/publisher/blocnames

# Update page
update:
    title: Edit Bloc Name
    redirect: waka/publisher/blocnames
    redirectClose: waka/publisher/blocnames

# Preview page
preview:
    title: Preview Bloc Name
