# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Bloc

# Model Form Field configuration
form: $/waka/publisher/models/bloc/fields.yaml

# Model Class name
modelClass: Waka\Publisher\Models\Bloc

# Default redirect location
defaultRedirect: waka/publisher/blocs

# Create page
create:
    title: Create Bloc
    redirect: waka/publisher/blocs/update/:id
    redirectClose: waka/publisher/blocs

# Update page
update:
    title: Edit Bloc
    redirect: waka/publisher/blocs
    redirectClose: waka/publisher/blocs

# Preview page
preview:
    title: Preview Bloc
